version: '3.3'

services:
  app:
    image: "ecrid.dkr.ecr.ap-southeast-2.amazonaws.com/app:${TAG}"
    build:
      context: .
      dockerfile: build/build.Dockerfile

  unittests:
    image: "app:unittest"
    build:
      context: .
      dockerfile: build/unittests.Dockerfile
    volumes:
       - ./UnitTestResults:/test/UnitTests/TestResults
